package com.mygrdaleframework.tests;
import org.junit.Test;

import com.acc.test.rap.RAP;

//import com.acc.test.rap.RAP;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'karimuddinmohammed' at '10/7/17 12:44 PM' with Gradle 2.14.1
 *
 * @author karimuddinmohammed, @date 10/7/17 12:44 PM
 */
public class LibraryTest extends RAP 
{
	
	static {
	      System.setProperty("env", "local");
	} 
	
	@Test
	public void aTest   () {
	
		assertTrue("karim".contains("karim"));
	}

	@Test
	public void bTest() {
	
		assertTrue("karim".contains("karim"));
	}
	@Test
	public void cTest() {
		
		assertTrue("karim".contains("karim"));
	}
	
	@Test
	public void dTest() {
		
		assertTrue("karim".contains("karim"));
	}
	
	@Test
	public void eTest() {
		
		assertTrue("karim".contains("karim"));
	}
	
	@Test
	public void fTest() {
		
		assertTrue("karim".contains("karim"));
	}
}
